---
functional:
  #Требования к регистрации и авторизации
  - Пользователь должен иметь возможность регистрации с почтой
  - Пользователь должен иметь возможность авторизации с почтой
  - Пользователь должен иметь возможность авторизации через Github
  - Пользователь должен иметь возможность авторизации через Discord
  #Тебования к главной странице
  - Пользователь должен видеть рейтинг среди пользователей игры
  - Пользователь должен иметь возможность присоединиться к игре
  - Пользователь должен видеть уровень сложности игр в лобби
  - Пользоватль должен видеть имена соперников и ботов в лобби
  - Пользоватль должен видеть название игр в лобби
  - Пользователь должен иметь возможность наблюдать за игрой других пользователей
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен видеть других пользователей, находящихся в сети
  - Пользователь должен иметь возможность просматривать турниры
  - Пользователь должен иметь возможность создать турнир
  #Требования к созданию новой игры
  - Пользователь должен иметь возможность выбирать уровень сложности игры
  - Пользователь должен иметь возможность выбрать соперником другого пользователя, друга и бота
  - Пользователь должен иметь возможность установить ограничение игры по времени
  - Пользователь должен иметь возможность играть в случайную игру
  - Пользователь должен иметь возможность выбора игры
  - В зависимости от выбора игры должны устанавливаться теги, по смыслу соответствующие игре
  #Требования к процессу игры
  - Пользователь должен иметь возможность просмотра руководства по игре
  - Пользователь должен иметь возможность остановить просмотр руководства на каждом из шагов
  - Пользователь должен иметь возможность выбора языка программирования
  - Пользователь должен иметь возможность видеть условие задачи на русском и английском языках
  - Пользователь должен иметь возможность видеть редактор кода соперника
  - Пользователь должен иметь возможность общения в чате во время игры
  - Пользователь должен иметь возможность навигации из игры и обратно
  - Пользователь должен иметь возможность сдаться
  - Пользователь должен иметь возможность сбросить написанный код
  - Пользователь должен иметь возможность проверить решение до окончания времени
  - Пользователь должен иметь возможность реванша
  - Пользователь должен увидеть результат игры
  - Пользователь должен иметь созможность смены оформления терминала
  #Требования к "после игры"
  - По результатам игры пользователю должны присваиваться очки
  - По количеству набранных пользователями очков должен составляться их рейтинг
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве 
  - Сайт должен быть совместим с последними версиями браузеров 
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь не можен повторно создавать одну и ту же игру, если выигрывал ее 
  - Пользователь не может создавать две игры одновременно 
  - Просмотр руководства пользователя не должно учитываться во времени на игру 
  - Пользователь не может влиять на ход решение соперника (менять его код и язык программирования)
  - Зрители поединков не могут вносить изменения в ход решения участников
  